### ISSUE TITLE
Incorrect usage example

### ISSUE THREAD

**Issue by senyai** [trundev/setup-gdal#1]
https://github.com/trundev/setup-gdal/blob/5e79fc02fd2ec7e1c0acda58a46cd7b3e4f5f84a/README.md?plain=1#L18
`Error: Unable to resolve action actions/setup-gdal, repository not found`

**Comment by trundev** [comment]
The README.md was referring to incorrect action-repository `actions` instead of `ttrundev`. This is fixed by commit id 4144577.
